### ISSUE TITLE
Adicionar imagem de modelo de skate

### ISSUE THREAD

**Issue by eduhoribe** [eduhoribe/poo06062019#1]
Procurar, baixar e referenciar uma imagem de um skate por inteiro para ser apresentado na tela de skates.
De preferência um gif animado.
Por favor colocar na pasta *poo06062019/src/br/edu/usf/poo/icon*

**Comment by matheusgtralli** [comment]
Added gif to the folder poo06062019/src/br/edu/usf/poo/icon
